### ISSUE TITLE
Error on OSX

### ISSUE THREAD

**Issue by petems** [wemanity-belgium/hyperclair#91] opened 2016-10-05 13:17 UTC
```
14:12:23  ! ~/clair_config $ hyperclair pull ZZROTDesign/alpine-ghost
client quit unexpectedly
FATA[0000] retrieving user: user: Current not implemented on darwin/amd64
```

Am I missing a setup step or does it not work on OSX?

**Comment by MercerAsian** [comment] 2016-10-26 15:27
I'm getting this same error

**Comment by oddcb** [comment] 2016-11-08 10:15
I installed Go via Homebrew, setup a go workspace and then did `go get github.com/wemanity-belgium` - then i went to `$HOME/my-go-workspace-path/src/github.com/wemanity-belgium/hyperclair` did `go build` and then `go run main.go` to run hyperclair. I think the issue might be cross-compilation from Linux which is not working as intended? Seems similar to this: https://github.com/golang/go/issues/6376

**Comment by jgsqware** [comment] 2017-02-22 15:56
Fixed in github.com/jgsqware/clairctl

**Closed by jgsqware** 2017-02-22 15:56 UTC
